// Copyright (c) 2025 Simsalabim Studios (Nils Bergemann). All rights reserved.
/*==========================================================================>
|              Gorgeous Events - Events functionality provider              |
| ------------------------------------------------------------------------- |
|         Copyright (C) 2025 Gorgeous Things by Simsalabim Studios,         |
|              administrated by Epic Nova. All rights reserved.             |
| ------------------------------------------------------------------------- |
|                   Epic Nova is an independent entity,                     |
|      that is has nothing in common with Epic Games in any capacity.       |
<==========================================================================*/
/*======================================================================================================================>
| --------------------------------------------------------------------------------------------------------------------- |
|                                   TO AVOID MISTAKES READ THIS BEFORE EDITING THIS FILE                                |
| --------------------------------------------------------------------------------------------------------------------- |
|                                DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!                              |
|           ONLY USE THIS FILE IN THE "GorgeousEvents*" MODULES, OTHERWISE INCLUDE THE NEEDED CLASSES MANUALLY          |
<======================================================================================================================*/
#pragma once

#include "GorgeousEventsRuntimeEnums.h"
#include "GorgeousEventsRuntimeGlobals.h"
#include "GorgeousEventsRuntimeLogging.h"
#include "GorgeousEventsRuntimeMacros.h"
#include "GorgeousEventsRuntimeStructures.h"